import _ from 'lodash';
import boostrap from 'bootstrap';
import './style.css';
import './build/css/custom.css';
import './build/css/custom.min.css';
import './fonts/css/font-awesome.css';
// import './build/js/custom.js';
// import './build/js/custom.min.js';
import './js/datepicker/daterangepicker.js';
import './css/maps/jquery-jvectormap-2.0.3.css';
import './scss/custom.scss';
import './scss/daterangepicker.scss';
import './javascript/custom.js';
import './javascript/helpers/smartresize.js';
// import './css/MyCss.css';
import 'datatables.net';
import 'datatables.net-dt/css/jquery.dataTables.css';
import './js/dataTableAward.js';
import './js/dataTableCrew.js';
import './js/t.js';
import './js/testadd.js';
import './js/crew_table.js';
import './js/award_table.js';
